#!/usr/bin/env python3
"""Publish a build of the web app to the BETA site (github.com/ubrowz/tailwind-tally-beta,
served at https://ubrowz.github.io/tailwind-tally-beta/), never to the released one.

  python3 tools/publish_beta.py [--ref next] [--dir ~/Software/tailwind-tally-beta] [--no-push]

It takes the web files from a git ref of THIS repository (committed state, so local
scratch files and routes are never included), makes them safe for a test site (noindex,
no visit counter, a visible beta banner, a "(beta)" title) and commits them to the beta
repository. The beta site shares the origin ubrowz.github.io with the released site, so
the map tiles (CORS) and the Strava callback keep working.
"""
import argparse, os, re, subprocess, sys

FILES = ["index.html", "privacy.html", "privacy-nl.html", "favicon.svg", "favicon-32.png", "apple-touch-icon.png", ".nojekyll"]
BETA_URL = "https://ubrowz.github.io/tailwind-tally-beta/"
RELEASED_URL = "https://ubrowz.github.io/tailwind-tally/"

BANNER_CSS = """
  .beta-banner { background: #fff3cd; color: #5c4400; border-bottom: 1px solid #e6cf85; font: 500 13px/1.4 system-ui, -apple-system, sans-serif;
    padding: 8px 16px; text-align: center; }
  .beta-banner a { color: inherit; }
  @media (prefers-color-scheme: dark) { .beta-banner { background: #3a3110; color: #f3e2a3; border-bottom-color: #6b5a1f; } }
"""
BANNER_HTML = ('<div class="beta-banner" id="betaBanner">Beta: a test version of Tailwind Tally, not the released app. '
               'The released app is at <a href="%s">%s</a>.</div>\n'
               '<script>if (/[?&]shots\\b/.test(location.search)) { var b = document.getElementById("betaBanner"); if (b) b.style.display = "none"; }</script>\n\n'
               % (RELEASED_URL, RELEASED_URL.replace("https://", "")))

def git(*args, cwd=None):
    return subprocess.run(["git", *args], cwd=cwd, check=True, capture_output=True, text=True).stdout

def betaify_index(html):
    assert "<title>Tailwind Tally</title>" in html, "unexpected title"
    html = html.replace("<title>Tailwind Tally</title>", '<title>Tailwind Tally (beta)</title>\n<meta name="robots" content="noindex, nofollow">', 1)
    html, n = re.subn(r'<!-- Visit counter.*?-->\s*<script data-goatcounter=.*?</script>\s*', '', html, flags=re.S)
    assert n == 1, "visit counter block not found"
    i = html.index('<div class="page">')
    j = html.rindex("</style>", 0, i)
    html = html[:j] + BANNER_CSS + html[j:]
    i = html.index('<div class="page">')
    return html[:i] + BANNER_HTML + html[i:]

def betaify_privacy(html):
    if 'name="robots"' in html:
        return html
    return re.sub(r"(<title>[^<]*</title>)", r'\1\n<meta name="robots" content="noindex, nofollow">', html, count=1)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ref", default="next")
    ap.add_argument("--dir", default=os.path.expanduser("~/Software/tailwind-tally-beta"))
    ap.add_argument("--no-push", action="store_true")
    a = ap.parse_args()
    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if not os.path.isdir(os.path.join(a.dir, ".git")):
        sys.exit("The beta repository is not checked out at %s (gh repo clone ubrowz/tailwind-tally-beta %s)" % (a.dir, a.dir))
    commit = git("rev-parse", "--short", a.ref, cwd=repo).strip()
    for name in FILES:
        try:
            data = subprocess.run(["git", "show", "%s:%s" % (a.ref, name)], cwd=repo, check=True, capture_output=True).stdout
        except subprocess.CalledProcessError:
            if name == ".nojekyll":
                data = b""
            elif name == "privacy-nl.html":      # not in branches from before the Dutch translation
                continue
            else:
                raise
        if name == "index.html":
            data = betaify_index(data.decode("utf-8")).encode("utf-8")
        elif name in ("privacy.html", "privacy-nl.html"):
            data = betaify_privacy(data.decode("utf-8")).encode("utf-8")
        with open(os.path.join(a.dir, name), "wb") as f:
            f.write(data)
    readme = ("# Tailwind Tally (beta)\n\nTest builds of [Tailwind Tally](%s), published from the `%s` branch of "
              "[ubrowz/tailwind-tally](https://github.com/ubrowz/tailwind-tally). **Not the released app**: it may change or break at any time.\n\n"
              "Live at %s (no search indexing, no visit counter).\n\nGenerated by `tools/publish_beta.py`; do not edit here.\n") % (RELEASED_URL, a.ref, BETA_URL)
    with open(os.path.join(a.dir, "README.md"), "w") as f:
        f.write(readme)
    git("add", "-A", cwd=a.dir)
    if not git("status", "--porcelain", cwd=a.dir).strip():
        print("Nothing changed: the beta site is already at %s." % commit); return
    git("commit", "-m", "Beta build from %s (%s)" % (a.ref, commit), cwd=a.dir)
    print("Committed beta build from %s (%s)." % (a.ref, commit))
    if not a.no_push:
        git("push", "origin", "HEAD", cwd=a.dir)
        print("Pushed. GitHub Pages rebuilds in about a minute: %s" % BETA_URL)

main()
